//! TAG
/** @typedef {'check_circle'|'arrow_back'|'cancel'|'add'|'toggle_on'|'open_in_new'|'more_vert'|'chevron_left'|'arrow_right_alt'|'arrow_drop_down'|'download'|'search'|'settings'|'refresh'|'check'|'favorite'|'delete'|'logout'|'check_box_outline_blank'|'home'|'chevron_right'|'arrow_forward'|'radio_button_checked'|'login'|'more_horiz'|'radio_button_unchecked'|'apps'|'menu'|'close'|'arrow_back_ios'|'check_box'|'arrow_forward_ios'|'star'|'add_circle'} IconSet0 */
/** @typedef {'do_not_disturb_on'|'keyboard_double_arrow_right'|'autorenew'|'done_outline'|'add_box'|'bolt'|'expand_circle_down'|'sort'|'double_arrow'|'restart_alt'|'undo'|'done_all'|'key'|'delete_forever'|'fullscreen'|'toggle_off'|'menu_open'|'ios_share'|'block'|'filter_list'|'filter_alt'|'remove'|'backspace'|'arrow_circle_right'|'sync_alt'|'arrow_downward'|'zoom_in'|'shopping_cart_checkout'|'arrow_upward'|'sync'|'arrow_back_ios_new'|'manage_search'|'drag_indicator'|'arrow_right'|'open_in_full'} IconSet1 */
/** @typedef {'swap_horiz'|'download_for_offline'|'upload'|'arrow_circle_left'|'library_add'|'file_open'|'settings_accessibility'|'create_new_folder'|'add_task'|'keyboard_double_arrow_left'|'cached'|'publish'|'minimize'|'forward'|'arrow_left'|'star_half'|'exit_to_app'|'unfold_more'|'arrow_drop_up'|'disabled_by_default'|'arrow_circle_up'|'keyboard_double_arrow_down'|'settings_applications'|'swap_vert'|'change_circle'|'downloading'|'app_registration'|'reply'|'close_fullscreen'|'redo'|'open_with'|'start'|'dataset'|'select_check_box'|'compare_arrows'} IconSet2 */
/** @typedef {'select_all'|'system_update_alt'|'unfold_less'|'settings_backup_restore'|'last_page'|'sync_problem'|'token'|'heart_plus'|'download_done'|'arrow_circle_down'|'indeterminate_check_box'|'delete_sweep'|'sort_by_alpha'|'filter_alt_off'|'arrow_outward'|'html'|'123'|'density_medium'|'arrow_drop_down_circle'|'subdirectory_arrow_right'|'keyboard_double_arrow_up'|'output'|'place_item'|'assistant_navigation'|'expand'|'swipe_left'|'search_off'|'clear_all'|'view_timeline'|'saved_search'|'fullscreen_exit'|'zoom_out'|'check_small'|'first_page'|'switch_access_shortcut'} IconSet3 */
/** @typedef {'assistant_direction'|'fit_screen'|'swap_horizontal_circle'|'switch_access_shortcut_add'|'swipe_down'|'hide_source'|'cycle'|'swap_vertical_circle'|'reply_all'|'javascript'|'apps_outage'|'css'|'move_up'|'compress'|'youtube_searched_for'|'dynamic_form'|'switch_left'|'install_desktop'|'swipe_right'|'maximize'|'enable'|'abc'|'browse_activity'|'progress_activity'|'density_small'|'view_kanban'|'star_rate'|'swipe_up'|'dataset_linked'|'restore_from_trash'|'keyboard_command_key'|'filter_list_off'|'data_thresholding'|'move_down'|'browse_gallery'} IconSet4 */
/** @typedef {'extension_off'|'hide'|'do_not_disturb_off'|'share_reviews'|'open_in_new_off'|'view_comfy_alt'|'switch_right'|'eject'|'key_off'|'unfold_more_double'|'prompt_suggestion'|'width_full'|'view_cozy'|'remove_done'|'pinch'|'width_wide'|'sync_disabled'|'file_download_off'|'more_up'|'repartition'|'density_large'|'expand_content'|'php'|'heart_minus'|'swipe_vertical'|'check_indeterminate_small'|'expand_all'|'width_normal'|'keyboard_control_key'|'send_time_extension'|'view_compact_alt'|'more_down'|'deployed_code'|'subdirectory_arrow_left'|'tab'} IconSet5 */
/** @typedef {'acute'|'keyboard_option_key'|'rule_settings'|'captive_portal'|'question_exchange'|'rebase'|'tab_unselected'|'swipe_down_alt'|'arrow_upward_alt'|'page_info'|'arrow_downward_alt'|'quick_reference'|'file_upload_off'|'clock_loader_10'|'stacks'|'quick_reference_all'|'collapse_all'|'unfold_less_double'|'chevron_forward'|'swipe_left_alt'|'stack'|'data_check'|'clock_loader_40'|'collapse_content'|'arrow_insert'|'swipe_up_alt'|'arrow_split'|'left_click'|'close_small'|'add_2'|'rebase_edit'|'clock_loader_60'|'hls'|'swipe_right_alt'|'hls_off'} IconSet6 */
/** @typedef {'stat_minus_1'|'unknown_med'|'new_window'|'side_navigation'|'deployed_code_update'|'stat_0'|'linked_services'|'category_search'|'step'|'arrow_range'|'action_key'|'directory_sync'|'data_alert'|'search_check'|'search_check_2'|'star_rate_half'|'drag_pan'|'switches'|'chevron_backward'|'arrow_left_alt'|'cards'|'expand_circle_right'|'data_info_alert'|'expand_circle_up'|'heart_check'|'arrows_output'|'clock_loader_20'|'highlight_mouse_cursor'|'sync_saved_locally'|'empty_dashboard'|'move_item'|'point_scan'|'modeling'|'event_list'|'file_export'} IconSet7 */
/** @typedef {'sweep'|'radio_button_partial'|'download_2'|'pip'|'resize'|'share_windows'|'arrow_upload_progress'|'stack_star'|'arrow_and_edge'|'settings_heart'|'clock_loader_90'|'steppers'|'iframe'|'right_panel_close'|'preliminary'|'responsive_layout'|'deployed_code_account'|'recenter'|'all_match'|'frame_bug'|'input_circle'|'clock_loader_80'|'right_panel_open'|'key_vertical'|'capture'|'toolbar'|'stat_3'|'arrows_input'|'left_panel_close'|'step_over'|'left_panel_open'|'bubble'|'arrow_back_2'|'dialogs'|'patient_list'} IconSet8 */
/** @typedef {'check_circle_unread'|'drag_click'|'switch_access_2'|'arrow_shape_up_stack_2'|'chronic'|'file_json'|'arrow_shape_up_stack'|'stat_1'|'sliders'|'tab_group'|'arrow_shape_up'|'deployed_code_history'|'chip_extraction'|'open_run'|'error_med'|'expansion_panels'|'stat_2'|'tab_search'|'right_click'|'stat_minus_2'|'move_group'|'multimodal_hand_eye'|'bubbles'|'bottom_navigation'|'arrows_outward'|'stat_minus_3'|'arrow_upload_ready'|'amend'|'app_badging'|'page_control'|'upload_2'|'step_into'|'borg'|'tab_duplicate'|'unknown_5'} IconSet9 */
/** @typedef {'arrow_top_right'|'open_in_new_down'|'clock_arrow_up'|'desktop_landscape'|'splitscreen_landscape'|'bucket_check'|'float_landscape_2'|'search_gear'|'tabs'|'back_to_tab'|'bottom_panel_open'|'clock_arrow_down'|'shelf_position'|'output_circle'|'switch_access'|'pip_exit'|'arrow_top_left'|'arrow_menu_open'|'tab_close'|'bottom_panel_close'|'magnification_large'|'reopen_window'|'arrow_or_edge'|'buttons_alt'|'deployed_code_alert'|'toast'|'frame_exclamation'|'bottom_drawer'|'filter_arrow_right'|'partner_reports'|'magnification_small'|'dropdown'|'jump_to_element'|'step_out'|'arrow_menu_close'} IconSet10 */
/** @typedef {'stack_off'|'tab_inactive'|'hourglass_arrow_up'|'hourglass_arrow_down'|'tab_move'|'bottom_right_click'|'timer_arrow_up'|'tab_new_right'|'sync_desktop'|'accessible_menu'|'fullscreen_portrait'|'rotate_auto'|'position_top_right'|'splitscreen_portrait'|'tab_recent'|'check_alert'|'move_selection_left'|'widget_width'|'timer_arrow_down'|'tile_small'|'ripples'|'bottom_sheets'|'sql'|'go_to_line'|'chips'|'view_apps'|'widget_medium'|'resize_window'|'subheader'|'position_bottom_right'|'edit_arrow_down'|'widget_small'|'stack_group'|'move_selection_right'|'shelf_auto_hide'} IconSet11 */
/** @typedef {'move_selection_down'|'widget_menu'|'swipe_right_2'|'tile_medium'|'sync_saved_locally_off'|'swipe_left_2'|'share'|'edit_arrow_up'|'person'|'highlight_text_cursor'|'person_add'|'tab_close_inactive'|'thumb_up'|'sync_arrow_up'|'position_bottom_left'|'splitscreen_landscape_add'|'tab_close_right'|'public'|'switch_access_3'|'group'|'page_menu_ios'|'thermostat_arrow_up'|'chevron_line_up'|'sync_arrow_down'|'iframe_off'|'desktop_portrait'|'bottom_app_bar'|'thermostat_arrow_down'|'highlight_keyboard_focus'|'move_selection_up'|'tile_large'|'groups'|'float_portrait_2'|'desktop_landscape_add'} IconSet12 */
/** @typedef {'support_agent'|'water_drop'|'diversity_1'|'mood'|'pets'|'eco'|'recommend'|'travel_explore'|'forest'|'sunny'|'emoji_people'|'diversity_3'|'health_and_safety'|'workspace_premium'|'rocket_launch'|'group_add'|'sentiment_very_satisfied'|'handshake'|'workspaces'|'face'|'thumb_down'|'psychology'|'sentiment_satisfied'|'vaccines'|'waving_hand'|'diamond'|'quiz'|'psychology_alt'|'sentiment_dissatisfied'|'gavel'|'military_tech'|'emoji_objects'|'monitor_heart'|'compost'|'recycling'} IconSet13 */
/** @typedef {'mood_bad'|'medication'|'group_work'|'rocket'|'medical_information'|'diversity_2'|'communication'|'groups_2'|'front_hand'|'sentiment_neutral'|'partner_exchange'|'coronavirus'|'person_remove'|'thumbs_up_down'|'cookie'|'heart_broken'|'emoji_nature'|'male'|'female'|'man'|'cruelty_free'|'woman'|'thunderstorm'|'solar_power'|'partly_cloudy_day'|'rainy'|'bedtime'|'potted_plant'|'sentiment_very_dissatisfied'|'add_reaction'|'wc'|'person_off'|'sentiment_extremely_dissatisfied'|'clear_day'|'connect_without_contact'} IconSet14 */
/** @typedef {'elderly'|'weight'|'masks'|'group_remove'|'person_2'|'pregnant_woman'|'public_off'|'groups_3'|'whatshot'|'egg'|'face_2'|'emoji_transportation'|'face_4'|'elderly_woman'|'boy'|'oil_barrel'|'transgender'|'identity_platform'|'co2'|'face_3'|'hive'|'bring_your_own_ip'|'routine'|'skull'|'emoji_food_beverage'|'sanitizer'|'face_6'|'medication_liquid'|'bloodtype'|'wind_power'|'reduce_capacity'|'follow_the_signs'|'south_america'|'clean_hands'|'sick'} IconSet15 */
/** @typedef {'egg_alt'|'woman_2'|'garden_cart'|'person_3'|'sunny_snowing'|'cognition'|'safety_divider'|'severe_cold'|'man_2'|'no_adult_content'|'outdoor_garden'|'foggy'|'tornado'|'partly_cloudy_night'|'sign_language'|'dentistry'|'vaping_rooms'|'neurology'|'landslide'|'person_4'|'volcano'|'cyclone'|'group_off'|'strategy'|'emoji_symbols'|'person_raised_hand'|'social_distance'|'blind'|'girl'|'18_up_rating'|'snowing'|'tsunami'|'face_5'|'tactic'|'flood'} IconSet16 */
/** @typedef {'eyeglasses_2'|'cognition_2'|'footprint'|'not_accessible'|'hand_bones'|'eyeglasses'|'editor_choice'|'man_4'|'sentiment_sad'|'communities'|'mystery'|'diamond_shine'|'stethoscope'|'man_3'|'psychiatry'|'diversity_4'|'rheumatology'|'mountain_flag'|'star_shine'|'radiology'|'crowdsource'|'orthopedics'|'labs'|'person_alert'|'bedtime_off'|'6_ft_apart'|'chess'|'rib_cage'|'person_check'|'digital_wellbeing'|'nutrition'|'social_leaderboard'|'skeleton'|'vape_free'|'vital_signs'} IconSet17 */
/** @typedef {'femur'|'clinical_notes'|'femur_alt'|'antigravity'|'ulna_radius_alt'|'brick'|'humerus_alt'|'specific_gravity'|'domino_mask'|'sentiment_stressed'|'lab_research'|'agender'|'family_star'|'cardiology'|'crossword'|'explosion'|'conversation'|'cheer'|'humerus'|'sentiment_calm'|'foot_bones'|'tibia'|'raven'|'demography'|'altitude'|'genetics'|'ulna_radius'|'conditions'|'tibia_alt'|'destruction'|'sentiment_frustrated'|'kid_star'|'breastfeeding'|'sentiment_excited'|'crown'} IconSet18 */
/** @typedef {'prescriptions'|'folded_hands'|'share_off'|'comic_bubble'|'bomb'|'partner_heart'|'person_cancel'|'barefoot'|'cookie_off'|'earthquake'|'sentiment_content'|'orbit'|'person_heart'|'weather_hail'|'home_health'|'blood_pressure'|'person_apron'|'guardian'|'stars_2'|'weather_mix'|'chef_hat'|'simulation'|'family_group'|'owl'|'heart_smile'|'cardio_load'|'deceased'|'pulse_alert'|'taunt'|'chess_pawn'|'pill'|'comedy_mask'|'emoticon'|'playing_cards'|'thumbs_up_double'} IconSet19 */
/** @typedef {'chess_queen'|'pregnancy'|'chess_knight'|'wrist'|'helicopter'|'menu_book_2'|'mood_heart'|'poker_chip'|'pulmonology'|'falling'|'health_cross'|'child_hat'|'metabolism'|'hand_package'|'snowing_heavy'|'sword_rose'|'water_bottle'|'skull_list'|'lab_panel'|'glucose'|'eyeglasses_2_sound'|'not_accessible_forward'|'recent_patient'|'mist'|'moon_stars'|'syringe'|'hand_meal'|'siren'|'sentiment_worried'|'ent'|'planet'|'allergy'|'globe_book'|'person_text'|'microbiology'} IconSet20 */
/** @typedef {'chess_bishop'|'dermatology'|'dew_point'|'procedure'|'symptoms'|'allergies'|'manga'|'chess_king'|'candle'|'face_nod'|'chess_rook'|'rainy_light'|'drone'|'rainy_heavy'|'cannabis'|'face_down'|'face_shake'|'surgical'|'rainy_snow'|'playground'|'water_do'|'oxygen_saturation'|'prayer_times'|'body_system'|'siren_question'|'stethoscope_check'|'siren_check'|'water_lux'|'pediatrics'|'square_dot'|'nephrology'|'infrared'|'mixture_med'|'oncology'|'admin_meds'} IconSet21 */
/** @typedef {'lips'|'respiratory_rate'|'oral_disease'|'hematology'|'humidity_percentage'|'medical_mask'|'massage'|'playground_2'|'congenital'|'wheat'|'acupuncture'|'body_fat'|'drone_2'|'fluid_balance'|'ward'|'moving_beds'|'stethoscope_arrow'|'water_orp'|'calendar_meal'|'water_ph'|'avocado_bean'|'chess_king_2'|'siren_open'|'shield_watch'|'dine_in'|'gastroenterology'|'immunology'|'face_left'|'gynecology'|'face_right'|'water_ec'|'outpatient'|'ophthalmology'|'snowflake'|'short_stay'} IconSet22 */
/** @typedef {'inpatient'|'fluid'|'water_bottle_large'|'water_drops'|'schedule'|'salinity'|'lock'|'total_dissolved_solids'|'table_sign'|'language'|'pill_off'|'wounds_injuries'|'sign_language_off'|'warning'|'fluid_med'|'outpatient_med'|'calendar_month'|'visibility_off'|'urology'|'visibility'|'chess_pawn_2'|'undereye'|'fork_chart'|'face_up'|'info'|'account_circle'|'error'|'chess_bishop_2'|'settings_seating'|'water_voc'|'eyebrow'|'verified'|'help'|'endocrinology'} IconSet23 */
/** @typedef {'lightbulb'|'history'|'fingerprint'|'how_to_reg'|'supervisor_account'|'alarm'|'event_available'|'question_mark'|'priority_high'|'power_settings_new'|'task_alt'|'category'|'celebration'|'today'|'touch_app'|'calendar_today'|'build'|'pending'|'stars'|'manage_accounts'|'lock_open'|'translate'|'bookmark'|'upload_file'|'code'|'account_box'|'preview'|'event'|'update'|'bug_report'|'date_range'|'terminal'|'edit_square'|'ads_click'|'extension'} IconSet24 */
/** @typedef {'pan_tool_alt'|'pan_tool'|'build_circle'|'hourglass_empty'|'event_note'|'accessibility_new'|'input'|'all_inclusive'|'priority'|'notification_important'|'rule'|'upgrade'|'help_center'|'web_asset'|'model_training'|'web'|'interests'|'wysiwyg'|'published_with_changes'|'bookmarks'|'hotel_class'|'supervised_user_circle'|'api'|'edit_calendar'|'circle_notifications'|'change_history'|'rate_review'|'support'|'manage_history'|'accessible'|'record_voice_over'|'event_upcoming'|'collections_bookmark'|'dangerous'|'label'} IconSet25 */
/** @typedef {'backup'|'event_repeat'|'square_foot'|'pageview'|'target'|'swipe'|'background_replace'|'home_app_logo'|'notification_add'|'lock_reset'|'dynamic_feed'|'label_important'|'save_as'|'more'|'no_accounts'|'bookmark_added'|'manufacturing'|'open_in_browser'|'perm_contact_calendar'|'flutter_dash'|'bookmark_add'|'free_cancellation'|'unpublished'|'more_time'|'approval'|'component_exchange'|'anchor'|'running_with_errors'|'webhook'|'accessibility'|'history_toggle_off'|'lock_person'|'event_busy'|'alarm_on'|'feedback'} IconSet26 */
/** @typedef {'hand_gesture'|'3d_rotation'|'add_alert'|'settings_power'|'http'|'arrow_selector_tool'|'code_off'|'commit'|'alarm_add'|'wifi_protected_setup'|'chrome_reader_mode'|'lock_clock'|'offline_pin'|'web_traffic'|'auto_delete'|'gesture'|'online_prediction'|'batch_prediction'|'hourglass_disabled'|'outbound'|'code_blocks'|'on_device_training'|'keep'|'find_replace'|'edit_notifications'|'lightbulb_circle'|'backup_table'|'pinch_zoom_out'|'pinch_zoom_in'|'new_label'|'domain_verification'|'accessible_forward'|'approval_delegation'|'bookmark_remove'|'snooze'} IconSet27 */
/** @typedef {'polymer'|'alarm_off'|'calendar_clock'|'user_attributes'|'timer_3_alt_1'|'voice_over_off'|'sticker'|'web_asset_off'|'time_auto'|'browse'|'sdk'|'label_off'|'data_loss_prevention'|'all_out'|'hourglass'|'pin_invoke'|'keep_off'|'rounded_corner'|'feature_search'|'award_star'|'problem'|'timer_10_alt_1'|'contacts_product'|'reminder'|'developer_guide'|'pin_end'|'settings_overscan'|'person_add_disabled'|'release_alert'|'lock_open_right'|'rsvp'|'logo_dev'|'lists'|'update_disabled'|'license'} IconSet28 */
/** @typedef {'bookmark_check'|'flutter'|'gesture_select'|'bookmark_flag'|'history_2'|'search_hands_free'|'ad_group'|'help_clinic'|'account_circle_off'|'select_window'|'delete_history'|'indeterminate_question_box'|'book_ribbon'|'account_child'|'wand_shine'|'draft_orders'|'watch_screentime'|'trackpad_input'|'person_edit'|'calendar_check'|'account_child_invert'|'add_ad'|'pan_zoom'|'bookmark_star'|'touch_long'|'wand_stars'|'ad'|'shift'|'keep_public'|'info_i'|'visibility_lock'|'circles_ext'|'select_window_2'|'settings_account_box'|'search_activity'} IconSet29 */
/** @typedef {'touch_double'|'approval_delegation_off'|'timer_pause'|'code_xml'|'lock_open_circle'|'history_off'|'pinboard'|'translate_indic'|'bookmark_bag'|'ad_group_off'|'shadow'|'preview_off'|'circles'|'shadow_add'|'warning_off'|'select_window_off'|'fingerprint_off'|'shift_lock'|'measuring_tape'|'unlicense'|'terminal_2'|'verified_off'|'power_settings_circle'|'domain_verification_off'|'timer_play'|'bookmark_heart'|'alarm_pause'|'supervised_user_circle_off'|'ad_off'|'bookmark_manager'|'hourglass_pause'|'alarm_smart_wake'|'bookmark_stacks'|'scrollable_header'|'water_lock'} IconSet30 */
/** @typedef {'notifications'|'chat'|'comment'|'forward_to_inbox'|'contact_support'|'forum'|'offline_pin_off'|'shadow_minus'|'send'|'pinboard_unread'|'alternate_email'|'inventory_2'|'calendar_lock'|'hourglass_check'|'contacts'|'hand_gesture_off'|'touch_double_2'|'import_contacts'|'shift_lock_off'|'sticker_add'|'person_search'|'notifications_active'|'link'|'mail'|'touch_triple'|'phone_in_talk'|'live_help'|'call'|'trackpad_input_2'|'chat_bubble'|'contact_mail'|'trackpad_input_3'|'sms'|'hub'} IconSet31 */
/** @typedef {'hourglass_top'|'unarchive'|'inbox'|'contact_phone'|'calendar_add_on'|'phone_enabled'|'call_end'|'drafts'|'schedule_send'|'g_translate'|'hourglass_bottom'|'mark_chat_unread'|'topic'|'lan'|'satellite_alt'|'mark_unread_chat_alt'|'move_to_inbox'|'notifications_off'|'mark_email_read'|'mode_comment'|'next_plan'|'call_made'|'3p'|'reviews'|'cell_tower'|'co_present'|'network_intelligence'|'mark_email_unread'|'cancel_presentation'|'speaker_notes'|'perm_phone_msg'|'dialpad'|'outgoing_mail'|'link_off'|'add_comment'} IconSet32 */
/** @typedef {'notifications_paused'|'picture_in_picture'|'spoke'|'mail_lock'|'phone_forwarded'|'picture_in_picture_alt'|'call_merge'|'contact_emergency'|'duo'|'chat_add_on'|'outbox'|'voice_chat'|'swap_calls'|'settings_phone'|'upcoming'|'call_split'|'phone_missed'|'attribution'|'attach_email'|'present_to_all'|'add_call'|'mark_as_unread'|'phone_callback'|'call_received'|'comment_bank'|'ring_volume'|'threat_intelligence'|'quickreply'|'cancel_schedule_send'|'phone_disabled'|'voicemail'|'all_inbox'|'unsubscribe'|'markunread_mailbox'|'mark_chat_read'} IconSet33 */
/** @typedef {'chat_apps_script'|'phone_bluetooth_speaker'|'phone_locked'|'wifi_calling'|'auto_read_play'|'wifi_channel'|'cell_wifi'|'rtt'|'score'|'send_and_archive'|'play_for_work'|'inbox_customize'|'comments_disabled'|'for_you'|'stacked_email'|'phone_paused'|'network_intel_node'|'pause_presentation'|'chat_info'|'e911_avatar'|'speaker_notes_off'|'speaker_phone'|'nat'|'group_search'|'dialer_sip'|'video_chat'|'sip'|'link_2'|'notifications_unread'|'settings_bluetooth'|'mms'|'auto_read_pause'|'calendar_apps_script'|'call_missed_outgoing'|'call_missed'} IconSet34 */
/** @typedef {'chat_error'|'picture_in_picture_small'|'picture_in_picture_mobile'|'ods'|'tooltip_2'|'chat_dashed'|'mail_shield'|'signal_cellular_add'|'picture_in_picture_center'|'call_quality'|'outbox_alt'|'call_log'|'inbox_text'|'network_manage'|'thread_unread'|'notification_multiple'|'picture_in_picture_off'|'mobile_cancel'|'wifi_add'|'notification_settings'|'stacked_inbox'|'network_intelligence_update'|'tooltip'|'network_intelligence_history'|'mail_asterisk'|'mobile_sound'|'notification_sound'|'chat_paste_go_2'|'mail_off'|'business_messages'|'inbox_text_share'|'inbox_text_person'|'notification_audio_off'|'chat_paste_go'|'notification_audio'} IconSet35 */
/** @typedef {'looks_one'|'phone_cancel'|'nature'|'picture_in_picture_medium'|'slideshow'|'chat_bubble_off'|'flash_on'|'add_a_photo'|'timelapse'|'picture_in_picture_large'|'imagesmode'|'timer'|'photo_library'|'add_photo_alternate'|'inbox_text_asterisk'|'crop_square'|'wb_sunny'|'mobile_sound_off'|'palette'|'picture_as_pdf'|'photo_camera'|'camera'|'odt'|'image'|'voice_chat_off'|'straighten'|'landscape'|'edit'|'auto_stories'|'brush'|'voicemail_2'|'wifi_proxy'|'tune'|'circle'} IconSet36 */
/** @typedef {'wb_incandescent'|'brightness_5'|'photo'|'image_search'|'contrast'|'brightness_6'|'compare'|'filter_vintage'|'style'|'rotate_right'|'colorize'|'aspect_ratio'|'center_focus_weak'|'broken_image'|'wb_twilight'|'filter_none'|'looks_two'|'animation'|'flare'|'blur_on'|'healing'|'grid_on'|'auto_awesome_motion'|'incomplete_circle'|'invert_colors'|'adjust'|'rotate_left'|'nature_people'|'filter_drama'|'center_focus_strong'|'looks_3'|'crop_free'|'crop'|'opacity'|'filter_center_focus'} IconSet37 */
/** @typedef {'loupe'|'flash_off'|'view_comfy'|'filter'|'flip_camera_ios'|'linked_camera'|'lens_blur'|'no_photography'|'photo_album'|'flaky'|'gif_box'|'flip_camera_android'|'transform'|'brightness_1'|'timer_off'|'flip'|'details'|'settings_brightness'|'crop_16_9'|'view_compact'|'control_point_duplicate'|'looks_4'|'dehaze'|'mic_external_on'|'auto_awesome_mosaic'|'brightness_4'|'hide_image'|'filter_1'|'brightness_7'|'exposure_plus_1'|'panorama'|'photo_camera_front'|'web_stories'|'grain'|'texture'} IconSet38 */
/** @typedef {'crop_7_5'|'shutter_speed'|'rotate_90_degrees_ccw'|'blur_circular'|'gradient'|'brightness_3'|'gif'|'crop_landscape'|'night_sight_auto'|'hdr_weak'|'filter_tilt_shift'|'rotate_90_degrees_cw'|'crop_portrait'|'leak_add'|'motion_photos_auto'|'hdr_auto'|'ev_shadow'|'camera_roll'|'crop_rotate'|'brightness_2'|'looks_6'|'tonality'|'motion_photos_paused'|'looks'|'flash_auto'|'vrpano'|'photo_frame'|'crop_5_4'|'exposure'|'looks_5'|'photo_size_select_small'|'filter_2'|'monochrome_photos'|'deblur'|'hdr_strong'} IconSet39 */
/** @typedef {'party_mode'|'filter_5'|'motion_blur'|'fluorescent'|'blur_medium'|'switch_video'|'burst_mode'|'filter_8'|'blur_linear'|'wb_iridescent'|'dirty_lens'|'hdr_on'|'blur_short'|'grid_off'|'face_retouching_off'|'filter_3'|'crop_3_2'|'timer_3'|'panorama_photosphere'|'filter_9_plus'|'panorama_horizontal'|'raw_on'|'exposure_zero'|'switch_camera'|'filter_frames'|'exposure_neg_1'|'exposure_plus_2'|'filter_7'|'timer_10'|'invert_colors_off'|'photo_size_select_large'|'macro_off'|'filter_4'|'filter_b_and_w'|'photo_camera_back'} IconSet40 */
/** @typedef {'30fps_select'|'image_aspect_ratio'|'filter_9'|'leak_remove'|'perm_camera_mic'|'wb_shade'|'hdr_auto_select'|'masked_transitions'|'gallery_thumbnail'|'vignette'|'hdr_on_select'|'filter_6'|'mic_external_off'|'24mp'|'night_sight_auto_off'|'panorama_vertical'|'18mp'|'panorama_wide_angle'|'exposure_neg_2'|'photo_prints'|'hdr_enhanced_select'|'10mp'|'no_flash'|'hdr_off'|'mp'|'autofps_select'|'settings_b_roll'|'trail_length'|'12mp'|'trail_length_medium'|'22mp'|'hevc'|'blur_off'|'trail_length_short'|'60fps_select'} IconSet41 */
/** @typedef {'13mp'|'2mp'|'settings_timelapse'|'6mp'|'wb_auto'|'5mp'|'19mp'|'planner_banner_ad_pt'|'vr180_create2d'|'raw_off'|'4mp'|'reset_settings'|'landscape_2'|'settings_photo_camera'|'motion_photos_on'|'settings_video_camera'|'9mp'|'15mp'|'photo_auto_merge'|'3mp'|'motion_play'|'16mp'|'21mp'|'hdr_off_select'|'14mp'|'23mp'|'8mp'|'7mp'|'image_arrow_up'|'hdr_plus'|'17mp'|'20mp'|'11mp'|'transition_push'|'crop_9_16'} IconSet42 */
/** @typedef {'high_res'|'gif_2'|'vr180_create2d_off'|'file_png'|'reset_brightness'|'image_inset'|'timer_2'|'settings_motion_mode'|'texture_add'|'background_grid_small'|'background_dot_large'|'settings_night_sight'|'motion_mode'|'macro_auto'|'settings_panorama'|'high_density'|'transition_dissolve'|'texture_minus'|'masked_transitions_add'|'filter_retrolux'|'transition_fade'|'low_density'|'reset_iso'|'50mp'|'background_dot_small'|'contrast_circle'|'settings_slow_motion'|'settings_cinematic_blur'|'shutter_speed_add'|'reset_focus'|'view_real_size'|'transition_slide'|'unknown_2'|'timer_1'|'shutter_speed_minus'} IconSet43 */
/** @typedef {'reset_shadow'|'attach_money'|'contrast_rtl_off'|'payments'|'mobile_camera_rear'|'account_balance'|'tonality_2'|'reset_white_balance'|'trending_up'|'ev_shadow_add'|'credit_card'|'monitoring'|'ev_shadow_minus'|'contrast_square'|'24fps_select'|'auto_stories_off'|'reset_shutter_speed'|'vignette_2'|'dropper_eye'|'crop_2_3'|'transition_chop'|'sell'|'database'|'mobile_camera_front'|'reset_exposure'|'hdr_plus_off'|'receipt_long'|'shopping_cart'|'shopping_bag'|'landscape_2_edit'|'storefront'|'crop_21_9'|'landscape_2_off'|'wb_twilight_2'} IconSet44 */
/** @typedef {'domain'|'work_history'|'work'|'insert_chart'|'meeting_room'|'bar_chart'|'loyalty'|'precision_manufacturing'|'account_tree'|'conversion_path'|'shopping_basket'|'show_chart'|'add_shopping_cart'|'credit_score'|'currency_exchange'|'receipt'|'query_stats'|'timeline'|'corporate_fare'|'euro'|'redeem'|'store'|'leaderboard'|'paid'|'trending_flat'|'calculate'|'qr_code'|'analytics'|'currency_rupee'|'pie_chart'|'qr_code_2'|'savings'|'account_balance_wallet'|'wallet'|'qr_code_scanner'} IconSet45 */
/** @typedef {'tenancy'|'production_quantity_limits'|'stacked_bar_chart'|'currency_bitcoin'|'room_preferences'|'finance_mode'|'barcode_scanner'|'atr'|'trending_down'|'remove_shopping_cart'|'donut_small'|'contactless'|'stacked_line_chart'|'copyright'|'add_business'|'currency_pound'|'barcode'|'track_changes'|'money_off'|'money'|'shop'|'data_exploration'|'add_card'|'area_chart'|'cases'|'toll'|'donut_large'|'price_change'|'add_chart'|'euro_symbol'|'schema'|'card_membership'|'price_check'|'bubble_chart'|'currency_yen'} IconSet46 */
/** @typedef {'bar_chart_4_bars'|'chart_data'|'strikethrough_s'|'enterprise'|'flowchart'|'ssid_chart'|'finance'|'atm'|'currency_ruble'|'currency_yuan'|'mediation'|'graph_3'|'money_bag'|'next_week'|'scatter_plot'|'orders'|'search_insights'|'waterfall_chart'|'credit_card_off'|'multiline_chart'|'currency_lira'|'data_table'|'full_stacked_bar_chart'|'card_travel'|'legend_toggle'|'domain_add'|'shop_two'|'network_node'|'domain_disabled'|'candlestick_chart'|'database_search'|'shoppingmode'|'grouped_bar_chart'|'no_meeting_room'|'troubleshoot'} IconSet47 */
/** @typedef {'universal_currency'|'graph_2'|'source_environment'|'currency_rupee_circle'|'database_upload'|'shopping_bag_speed'|'energy'|'credit_card_clock'|'mitre'|'percent_discount'|'conveyor_belt'|'checkbook'|'currency_franc'|'graph_5'|'bid_landscape'|'credit_card_heart'|'graph_1'|'delivery_truck_speed'|'order_approve'|'cards_star'|'planner_review'|'money_range'|'universal_currency_alt'|'podium'|'quick_reorder'|'delivery_truck_bolt'|'graph_4'|'forklift'|'graph_7'|'mintmark'|'flowsheet'|'contactless_off'|'box'|'send_money'|'family_history'} IconSet48 */
/** @typedef {'upi_pay'|'work_update'|'payment_arrow_down'|'map'|'box_add'|'front_loader'|'box_edit'|'payment_card'|'pin_drop'|'explore'|'order_play'|'work_alert'|'trolley'|'qr_code_2_add'|'graph_8'|'inactive_order'|'conversion_path_off'|'sell_cloud'|'my_location'|'flag'|'home_pin'|'credit_card_gear'|'bar_chart_off'|'shopping_cart_off'|'location_on'|'graph_6'|'restaurant'|'briefcase_meal'|'barcode_reader'|'database_off'|'enterprise_off'|'pallet'|'receipt_long_off'|'bid_landscape_disabled'} IconSet49 */
/** @typedef {'local_mall'|'factory'|'zoom_out_map'|'near_me'|'person_pin'|'where_to_vote'|'local_gas_station'|'emergency'|'handyman'|'park'|'navigation'|'crisis_alert'|'local_florist'|'add_location'|'local_hospital'|'local_library'|'south'|'fastfood'|'local_police'|'layers'|'location_away'|'business_center'|'local_fire_department'|'east'|'west'|'north_east'|'home_repair_service'|'person_pin_circle'|'location_searching'|'local_parking'|'medical_services'|'warehouse'|'share_location'|'home_work'|'local_activity'} IconSet50 */
/** @typedef {'360'|'not_listed_location'|'north'|'local_pizza'|'local_atm'|'wine_bar'|'local_post_office'|'church'|'safety_check'|'theater_comedy'|'electrical_services'|'pest_control'|'flag_circle'|'alt_route'|'traffic'|'takeout_dining'|'add_location_alt'|'package'|'cleaning_services'|'beenhere'|'fmd_bad'|'signpost'|'local_convenience_store'|'tour'|'globe'|'local_laundry_service'|'local_drink'|'trip_origin'|'maps_ugc'|'location_off'|'moving'|'directions'|'ev_station'|'location_home'|'zoom_in_map'} IconSet51 */
/** @typedef {'airline_stops'|'edit_attributes'|'stadium'|'local_car_wash'|'baby_changing_station'|'minor_crash'|'castle'|'fire_truck'|'run_circle'|'plumbing'|'set_meal'|'mode_of_travel'|'mosque'|'kebab_dining'|'local_pharmacy'|'edit_location'|'transfer_within_a_station'|'soup_kitchen'|'satellite'|'package_2'|'streetview'|'add_road'|'south_west'|'transit_enterexit'|'wrong_location'|'edit_location_alt'|'connecting_airports'|'layers_clear'|'multiple_stop'|'add_home'|'sos'|'edit_road'|'south_east'|'dry_cleaning'|'north_west'} IconSet52 */
/** @typedef {'near_me_disabled'|'file_map'|'map_search'|'compass_calibration'|'pest_control_rodent'|'share_eta'|'explore_nearby'|'universal_local'|'pergola'|'pet_supplies'|'flight_class'|'no_meals'|'temple_buddhist'|'local_see'|'temple_hindu'|'things_to_do'|'assist_walker'|'moved_location'|'explore_off'|'add_home_work'|'globe_location_pin'|'add_triangle'|'fort'|'globe_asia'|'directions_alt'|'flag_check'|'globe_uk'|'fire_hydrant'|'flag_2'|'synagogue'|'map_pin_heart'|'directions_off'|'location_disabled'|'remove_road'|'directions_alt_off'} IconSet53 */
/** @typedef {'meal_dinner'|'pin_road'|'parent_child_dining'|'multiple_airports'|'meal_lunch'|'shaved_ice'|'list'|'file_map_stack'|'move_location'|'udon'|'move'|'rest_area'|'tatami_seat'|'grid_view'|'moving_ministry'|'tilt_arrow_up'|'hanami_dango'|'safety_check_off'|'soba'|'pin_road_2'|'edit_note'|'award_meal'|'kanji_alcohol'|'solo_dining'|'map_pin_review'|'calendar_meal_2'|'takeout_dining_2'|'menu_book'|'description'|'yakitori'|'pin_history'|'dashboard'|'content_copy'|'tilt_arrow_down'} IconSet54 */
/** @typedef {'list_alt'|'summarize'|'article'|'post_add'|'drag_handle'|'newspaper'|'file_copy'|'note_add'|'archive'|'task'|'space_dashboard'|'content_paste'|'cloud_upload'|'folder_open'|'inventory'|'assignment'|'book'|'history_edu'|'checklist'|'request_quote'|'attach_file'|'folder'|'draw'|'cloud'|'view_list'|'draft'|'fact_check'|'design_services'|'pending_actions'|'table'|'contact_page'|'format_quote'|'border_color'|'format_list_bulleted'|'cloud_download'} IconSet55 */
/** @typedef {'docs'|'title'|'folder_shared'|'integration_instructions'|'checklist_rtl'|'note_alt'|'document_scanner'|'content_cut'|'text_fields'|'assignment_turned_in'|'format_italic'|'data_object'|'dashboard_customize'|'edit_document'|'format_color_fill'|'format_bold'|'notes'|'perm_media'|'cloud_done'|'find_in_page'|'text_snippet'|'table_chart'|'percent'|'sticky_note_2'|'content_paste_search'|'tag'|'subject'|'cloud_sync'|'attachment'|'table_rows'|'reorder'|'format_list_numbered'|'assignment_ind'|'table_view'|'functions'} IconSet56 */
/** @typedef {'format_color_text'|'copy_all'|'square'|'read_more'|'format_size'|'file_present'|'difference'|'format_underlined'|'drive_file_move'|'format_align_left'|'folder_copy'|'view_column'|'view_module'|'grading'|'team_dashboard'|'folder_special'|'ballot'|'plagiarism'|'view_week'|'polyline'|'view_agenda'|'assignment_late'|'vertical_align_top'|'format_paint'|'segment'|'toc'|'horizontal_rule'|'calendar_view_month'|'assignment_return'|'drive_folder_upload'|'add_link'|'cloud_off'|'height'|'vertical_align_bottom'|'low_priority'} IconSet57 */
/** @typedef {'request_page'|'breaking_news_alt_1'|'view_sidebar'|'font_download'|'format_shapes'|'calendar_view_day'|'folder_zip'|'cloud_circle'|'format_align_center'|'files'|'join_inner'|'counter_1'|'hexagon'|'format_align_right'|'docs_add_on'|'calendar_view_week'|'edit_off'|'imagesearch_roller'|'view_carousel'|'numbers'|'view_headline'|'add_to_drive'|'folder_delete'|'pages'|'automation'|'video_file'|'content_paste_go'|'view_quilt'|'format_align_justify'|'format_list_numbered_rtl'|'forms_add_on'|'rule_folder'|'linear_scale'|'text_increase'|'text_format'} IconSet58 */
/** @typedef {'line_weight'|'contract'|'pivot_table_chart'|'vertical_align_center'|'restore_page'|'assignment_returned'|'vertical_split'|'view_stream'|'merge_type'|'join_left'|'align_horizontal_left'|'subtitles_off'|'newsmode'|'counter_3'|'join_right'|'horizontal_split'|'counter_2'|'format_line_spacing'|'deselect'|'function'|'spellcheck'|'pentagon'|'short_text'|'shape_line'|'flip_to_front'|'format_color_reset'|'rectangle'|'space_bar'|'view_day'|'text_decrease'|'contract_edit'|'border_all'|'data_array'|'format_strikethrough'|'format_indent_increase'} IconSet59 */
/** @typedef {'line_style'|'ink_pen'|'align_horizontal_center'|'insert_page_break'|'document_search'|'finance_chip'|'folder_off'|'frame_inspect'|'flip_to_back'|'align_vertical_top'|'ink_eraser'|'horizontal_distribute'|'snippet_folder'|'news'|'vertical_distribute'|'line_axis'|'dictionary'|'book_2'|'wrap_text'|'overview'|'align_vertical_center'|'glyphs'|'note_stack'|'format_indent_decrease'|'format_clear'|'align_vertical_bottom'|'ink_highlighter'|'content_paste_off'|'clarify'|'superscript'|'equal'|'list_alt_check'|'assignment_add'|'join'|'align_horizontal_right'} IconSet60 */
/** @typedef {'csv'|'full_coverage'|'file_save'|'unknown_document'|'shapes'|'border_style'|'lab_profile'|'colors'|'signature'|'view_array'|'subscript'|'add_notes'|'format_textdirection_l_to_r'|'margin'|'docs_apps_script'|'border_vertical'|'book_5'|'article_person'|'text_rotation_none'|'view_column_2'|'export_notes'|'breaking_news'|'text_rotate_vertical'|'border_horizontal'|'amp_stories'|'counter_4'|'select'|'font_download_off'|'border_clear'|'note_stack_add'|'forms_apps_script'|'border_outer'|'rubric'|'padding'|'type_specimen'} IconSet61 */
/** @typedef {'text_ad'|'text_rotate_up'|'book_4'|'border_bottom'|'text_rotation_down'|'draw_abstract'|'text_compare'|'text_rotation_angledown'|'asterisk'|'text_rotation_angleup'|'text_fields_alt'|'cell_merge'|'match_case'|'slide_library'|'format_h1'|'format_overline'|'grid_guides'|'cloud_lock'|'format_textdirection_r_to_l'|'border_right'|'frame_source'|'border_left'|'cloud_alert'|'drive_file_rename'|'article_shortcut'|'diagnosis'|'remove_selection'|'ink_selection'|'folder_limited'|'voting_chip'|'format_ink_highlighter'|'table_chart_view'|'border_top'|'counter_5'|'border_inner'} IconSet62 */
/** @typedef {'table_rows_narrow'|'regular_expression'|'format_paragraph'|'table_eye'|'folder_managed'|'person_book'|'list_alt_add'|'custom_typography'|'assignment_globe'|'source_notes'|'brand_family'|'line_curve'|'counter_6'|'markdown'|'stock_media'|'line_end_circle'|'two_pager'|'dashboard_2_gear'|'attach_file_add'|'format_h2'|'drive_export'|'lasso_select'|'convert_to_text'|'reset_image'|'scan'|'insert_text'|'process_chart'|'variables'|'dashboard_2'|'format_underlined_squiggle'|'folder_data'|'view_object_track'|'format_image_left'|'folder_code'|'format_list_bulleted_add'} IconSet63 */
/** @typedef {'diagonal_line'|'folder_check'|'format_letter_spacing'|'stylus_laser_pointer'|'file_copy_off'|'ungroup'|'format_image_right'|'format_letter_spacing_standard'|'counter_0'|'scan_delete'|'line_end'|'sticky_note'|'location_chip'|'add_column_right'|'cards_stack'|'ink_marker'|'line_end_arrow_notch'|'other_admission'|'line_end_arrow'|'business_chip'|'text_select_start'|'fit_width'|'counter_9'|'folder_supervised'|'ink_highlighter_move'|'counter_8'|'variable_insert'|'format_h3'|'line_start_circle'|'variable_add'|'contract_delete'|'smb_share'|'stroke_partial'|'folder_eye'|'counter_7'} IconSet64 */
/** @typedef {'fit_page_width'|'book_3'|'post'|'folder_info'|'markdown_copy'|'draw_collage'|'stroke_full'|'pageless'|'match_word'|'text_select_move_forward_character'|'pen_size_1'|'folder_match'|'dashboard_2_edit'|'folder_check_2'|'line_start_diamond'|'language_spanish'|'format_h5'|'stack_hexagon'|'two_pager_store'|'format_h4'|'frame_reload'|'text_select_end'|'line_start'|'format_h6'|'file_save_off'|'language_korean_latin'|'decimal_increase'|'pen_size_2'|'format_text_overflow'|'line_end_diamond'|'flex_wrap'|'combine_columns'|'book_6'|'format_letter_spacing_2'|'table_edit'} IconSet65 */
/** @typedef {'text_select_move_forward_word'|'pen_size_5'|'pen_size_4'|'align_justify_space_even'|'flex_direction'|'letter_switch'|'language_international'|'align_center'|'table_convert'|'language_chinese_quick'|'highlighter_size_3'|'text_select_move_back_word'|'script'|'match_case_off'|'thumbnail_bar'|'fit_page'|'fit_page_height'|'text_select_move_down'|'top_panel_close'|'format_letter_spacing_wide'|'language_us'|'attach_file_off'|'line_start_arrow_notch'|'align_justify_space_between'|'grid_layout_side'|'format_letter_spacing_wider'|'titlecase'|'stylus_fountain_pen'|'language_japanese_kana'|'add_row_below'|'line_end_square'|'pen_size_3'|'align_items_stretch'|'highlighter_size_5'|'heap_snapshot_thumbnail'} IconSet66 */
/** @typedef {'flex_no_wrap'|'top_panel_open'|'add_row_above'|'stylus_pencil'|'tsv'|'format_paint_off'|'align_justify_flex_start'|'language_chinese_cangjie'|'line_start_square'|'variable_remove'|'markdown_paste'|'align_justify_space_around'|'page_header'|'text_select_move_up'|'add_column_left'|'language_chinese_dayi'|'sheets_rtl'|'special_character'|'highlighter_size_4'|'page_footer'|'slab_serif'|'align_flex_center'|'line_start_arrow'|'language_gb_english'|'text_select_jump_to_end'|'eraser_size_5'|'highlighter_size_1'|'heap_snapshot_multiple'|'ink_eraser_off'|'format_text_wrap'|'eraser_size_1'|'heap_snapshot_large'|'language_french'|'highlighter_size_2'|'text_select_jump_to_beginning'} IconSet67 */
/** @typedef {'list_arrow'|'language_chinese_pinyin'|'horizontal_align_left'|'align_space_even'|'eraser_size_3'|'align_stretch'|'language_us_dvorak'|'language_pinyin'|'align_flex_end'|'text_select_move_back_character'|'language_chinese_wubi'|'align_self_stretch'|'align_flex_start'|'horizontal_align_center'|'align_space_around'|'language_chinese_array'|'eraser_size_4'|'format_text_clip'|'format_image_back'|'format_image_front'|'text_ad_off'|'dashboard_2_add'|'stylus_brush'|'align_justify_center'|'uppercase'|'align_justify_stretch'|'format_quote_off'|'decimal_decrease'|'align_end'|'serif'|'space_dashboard_2'|'align_justify_flex_end'|'align_start'|'align_space_between'|'eraser_size_2'} IconSet68 */
/** @typedef {'horizontal_align_right'|'fiber_manual_record'|'skip_previous'|'format_image_break_left'|'format_image_break_right'|'lowercase'|'subscriptions'|'view_in_ar'|'play_arrow'|'ink_highlighter_off'|'speed'|'format_image_inline_right'|'volume_up'|'pause'|'play_circle'|'stylus_highlighter'|'videocam'|'movie'|'replay'|'volume_off'|'stylus_pen'|'library_books'|'pause_circle'|'format_image_inline_left'|'skip_next'|'stop'|'music_note'|'equalizer'|'text_up'|'video_library'|'language_us_colemak'|'stop_circle'|'format_textdirection_vertical'|'mic'} IconSet69 */
/** @typedef {'podcasts'|'fast_rewind'|'volume_down'|'radio'|'sound_detection_dog_barking'|'playlist_play'|'video_camera_front'|'not_started'|'shuffle'|'playlist_add_check'|'volume_mute'|'hearing'|'queue_music'|'videocam_off'|'subtitles'|'video_call'|'av_timer'|'text_to_speech'|'library_add_check'|'play_pause'|'repeat'|'closed_caption'|'stream'|'interpreter_mode'|'album'|'discover_tune'|'replay_10'|'branding_watermark'|'playlist_remove'|'fast_forward'|'mic_off'|'forward_10'|'fiber_new'|'playlist_add'|'library_music'} IconSet70 */
/** @typedef {'add_to_queue'|'featured_video'|'high_quality'|'4k'|'call_to_action'|'featured_play_list'|'repeat_on'|'speech_to_text'|'spatial_audio_off'|'playlist_add_circle'|'explicit'|'video_camera_back'|'hearing_disabled'|'play_lesson'|'hd'|'replay_5'|'recent_actors'|'music_off'|'sound_detection_loud_sound'|'spatial_audio'|'brand_awareness'|'playlist_add_check_circle'|'art_track'|'forward_30'|'frame_person'|'audio_file'|'repeat_one'|'slow_motion_video'|'settings_voice'|'airplay'|'queue_play_next'|'lyrics'|'voice_selection'|'shuffle_on'|'video_settings'} IconSet71 */
/** @typedef {'video_stable'|'1k'|'30fps'|'10k'|'missed_video_call'|'forward_5'|'replay_30'|'music_cast'|'broadcast_on_home'|'digital_out_of_home'|'video_label'|'remove_from_queue'|'broadcast_on_personal'|'ar_on_you'|'sound_detection_glass_break'|'spatial_tracking'|'adaptive_audio_mic'|'4k_plus'|'fiber_smart_record'|'8k'|'closed_caption_disabled'|'animated_images'|'sd'|'surround_sound'|'fiber_dvr'|'60fps'|'music_video'|'instant_mix'|'privacy'|'play_disabled'|'resume'|'control_camera'|'repeat_one_on'|'eye_tracking'|'fiber_pin'} IconSet72 */
/** @typedef {'video_camera_front_off'|'cinematic_blur'|'mic_double'|'7k'|'genres'|'ear_sound'|'1k_plus'|'music_note_2'|'media_link'|'8k_plus'|'forward_media'|'6k'|'2k'|'3k_plus'|'frame_person_mic'|'6k_plus'|'5k'|'2k_plus'|'3k'|'movie_edit'|'9k_plus'|'artist'|'speed_2x'|'7k_plus'|'video_search'|'video_camera_back_add'|'autoplay'|'autopause'|'split_scene'|'no_sound'|'hangout_video'|'5k_plus'|'9k'|'mic_alert'|'adaptive_audio_mic_off'} IconSet73 */
/** @typedef {'replace_video'|'full_hd'|'music_note_add'|'replace_image'|'2d'|'speed_1_5x'|'autostop'|'speed_0_2x'|'speed_1_25'|'split_scene_down'|'select_to_speak'|'speed_0_5'|'speed_4'|'movie_speaker'|'speed_1_2x'|'hearing_aid'|'speed_0_75'|'closed_caption_add'|'speed_2'|'ar_stickers'|'movie_info'|'split_scene_up'|'av1'|'speed_0_7x'|'split_scene_left'|'forward_circle'|'3d'|'subtitles_gear'|'frame_person_off'|'audio_description'|'replace_audio'|'speed_1_5'|'edit_audio'|'speed_0_5x'|'speed_3'} IconSet74 */
/** @typedef {'flight_takeoff'|'video_template'|'movie_edit_off'|'video_frame_save'|'sound_sampler'|'2d_2'|'speed_1_2'|'speed_1_7x'|'flight'|'split_scene_2'|'voice_selection_off'|'hearing_aid_disabled_left'|'hearing_aid_disabled'|'mic_gear'|'3d_2'|'directions_bus'|'videocam_alert'|'speed_0_25'|'movie_off'|'split_scene_right'|'train'|'view_in_ar_off'|'speed_1_75'|'directions_run'|'hearing_aid_left'|'avc'|'audio_capture'|'directions_car'|'music_history'|'local_shipping'|'video_frame_copy'|'directions_walk'|'spatial_speaker'|'hangout_video_off'} IconSet75 */
/** @typedef {'bus_alert'|'tram'|'turn_right'|'electric_car'|'directions_bike'|'departure_board'|'subway'|'turn_slight_right'|'pedal_bike'|'airport_shuttle'|'flight_land'|'sailing'|'electric_rickshaw'|'car_crash'|'two_wheeler'|'commute'|'airlines'|'directions_boat'|'transportation'|'taxi_alert'|'fork_right'|'turn_left'|'rv_hookup'|'motorcycle'|'u_turn_left'|'agriculture'|'electric_bike'|'directions_subway'|'electric_scooter'|'hail'|'tire_repair'|'local_taxi'|'electric_moped'|'no_crash'|'directions_railway'} IconSet76 */
/** @typedef {'u_turn_right'|'turn_sharp_right'|'flyover'|'road'|'bike_scooter'|'ambulance'|'unpaved_road'|'turn_sharp_left'|'windshield_defrost_front'|'plane_contrails'|'traffic_jam'|'turn_slight_left'|'speed_camera'|'auto_transmission'|'transit_ticket'|'car_fan_recirculate'|'directions_railway_2'|'swap_driving_apps_wheel'|'car_gear'|'fork_left'|'bus_railway'|'bike_lane'|'no_transfer'|'railway_alert'|'parking_sign'|'car_fan_low_left'|'moped'|'car_tag'|'garage_money'|'gondola_lift'|'auto_towing'|'hov'|'fan_indirect'|'snowmobile'|'swap_driving_apps'} IconSet77 */
/** @typedef {'monorail'|'boat_bus'|'subway_walk'|'garage_check'|'fan_focus'|'car_fan_mid_low_right'|'scooter'|'windshield_defrost_auto'|'car_defrost_low_right'|'cable_car'|'seat_heat_right'|'car_fan_mid_right'|'funicular'|'windshield_defrost_rear'|'seat_heat_left'|'seat_cool_right'|'parking_meter'|'car_fan_recirculate_2'|'car_defrost_mid_low_left'|'seat_vent_right'|'seat_cool_left'|'car_fan_low_right'|'car_fan_mid_left'|'metro'|'bike_dock'|'car_fan_low_mid_left'|'car_mirror_heat'|'car_defrost_left'|'hvac_max_defrost'|'moped_package'|'car_lock'|'parking_valet'|'steering_wheel_heat'|'railway_alert_2'|'bus_map_pin'} IconSet78 */
/** @typedef {'sports_basketball'|'air'|'personal_injury'|'sports_esports'|'waves'|'volunteer_activism'|'seat_vent_left'|'science'|'sports_soccer'|'car_defrost_right'|'sports_score'|'architecture'|'car_defrost_mid_right'|'windshield_heat_front'|'construction'|'hiking'|'trolley_cable_car'|'confirmation_number'|'experiment'|'biotech'|'real_estate_agent'|'car_defrost_low_left'|'walk_bike'|'trophy'|'boat_railway'|'car_defrost_mid_left'|'school'|'car_defrost_mid_low_right'|'theaters'|'water'|'campaign'|'self_improvement'|'engineering'|'cake'} IconSet79 */
/** @typedef {'toys'|'switch_account'|'featured_seasonal_and_gifts'|'phishing'|'how_to_vote'|'sports_kabaddi'|'sports_martial_arts'|'sports_football'|'nordic_walking'|'sports_mma'|'backpack'|'rowing'|'sports_tennis'|'sports_cricket'|'sports_motorsports'|'scuba_diving'|'scoreboard'|'surfing'|'camping'|'downhill_skiing'|'storm'|'roller_skating'|'skateboarding'|'sports'|'sports_volleyball'|'kitesurfing'|'sports_gymnastics'|'toys_fan'|'swords'|'sports_handball'|'kayaking'|'sports_golf'|'piano'|'rewarded_ads'|'sports_baseball'} IconSet80 */
/** @typedef {'toys_and_games'|'person_play'|'piano_off'|'service_toolbox'|'sports_rugby'|'sports_hockey'|'elevation'|'readiness_score'|'arrow_warm_up'|'azm'|'distance'|'snowshoeing'|'snowboarding'|'sprint'|'paragliding'|'arrow_cool_down'|'health_metrics'|'person_celebrate'|'steps'|'no_backpack'|'avg_time'|'sledding'|'laps'|'ice_skating'|'mindfulness'|'exercise'|'sports_and_outdoors'|'ecg_heart'|'floor'|'avg_pace'|'interactive_space'|'pace'|'ifl'|'newsstand'|'family_link'} IconSet81 */
/** @typedef {'cake_add'|'cadence'|'shoe_cleats'|'books_movies_and_music'|'stress_management'|'eda'|'cleaning'|'water_loss'|'bia'|'water_medium'|'menstrual_health'|'onsen'|'check_in_out'|'relax'|'bath_private'|'monitor_weight_loss'|'glass_cup'|'fertile'|'monitor_weight_gain'|'vo2_max'|'hr_resting'|'water_full'|'sauna'|'podiatry'|'science_off'|'padel'|'bath_public_large'|'badminton'|'bath_outdoor'|'spo2'|'pickleball'|'sleep_score'|'dark_mode'|'physical_therapy'} IconSet82 */
/** @typedef {'gpp_bad'|'cameraswitch'|'rss_feed'|'charger'|'signal_cellular_alt'|'nightlight'|'battery_full_alt'|'battery_4_bar'|'battery_6_bar'|'radar'|'password'|'signal_wifi_4_bar'|'light_mode'|'signal_disconnected'|'battery_0_bar'|'gpp_maybe'|'bluetooth'|'android'|'network_check'|'wifi_off'|'pin'|'graphic_eq'|'wifi'|'battery_charging_full'|'widgets'|'wallpaper'|'thermostat'|'storage'|'cable'|'flashlight_on'|'data_usage'|'signal_cellular_4_bar'|'battery_full'|'battery_5_bar'|'dvr'} IconSet83 */
/** @typedef {'wifi_find'|'signal_cellular_3_bar'|'battery_low'|'data_saver_on'|'battery_charging_90'|'adb'|'network_wifi'|'quick_phrases'|'noise_control_off'|'bluetooth_disabled'|'network_cell'|'signal_wifi_statusbar_not_connected'|'battery_2_bar'|'signal_wifi_bad'|'network_wifi_1_bar'|'battery_charging_80'|'network_wifi_3_bar'|'wifi_tethering'|'brightness_medium'|'bluetooth_connected'|'usb'|'splitscreen'|'battery_3_bar'|'nfc'|'mobiledata_off'|'5g'|'battery_alert'|'signal_wifi_off'|'pattern'|'battery_1_bar'|'ios'|'mode_standby'|'bluetooth_searching'|'network_wifi_2_bar'|'sim_card_download'} IconSet84 */
/** @typedef {'signal_cellular_nodata'|'perm_data_setting'|'grid_3x3'|'signal_wifi_statusbar_null'|'wifi_2_bar'|'noise_aware'|'battery_very_low'|'signal_cellular_connected_no_internet_0_bar'|'battery_unknown'|'airplanemode_inactive'|'devices_fold'|'4g_mobiledata'|'1x_mobiledata'|'signal_cellular_0_bar'|'signal_wifi_0_bar'|'grid_4x4'|'signal_cellular_2_bar'|'signal_cellular_alt_2_bar'|'wifi_tethering_error'|'do_not_disturb_on_total_silence'|'signal_cellular_connected_no_internet_4_bar'|'settings_system_daydream'|'screen_rotation_alt'|'badge_critical_battery'|'battery_charging_60'|'wifi_lock'|'battery_charging_30'|'battery_charging_20'|'nearby_error'|'battery_charging_50'|'brightness_auto'|'network_ping'|'flashlight_off'|'lte_mobiledata'|'signal_cellular_1_bar'} IconSet85 */
/** @typedef {'4g_plus_mobiledata'|'usb_off'|'signal_cellular_off'|'contextual_token'|'noise_control_on'|'g_mobiledata'|'media_bluetooth_on'|'3g_mobiledata'|'wifi_tethering_off'|'signal_cellular_alt_1_bar'|'perm_scan_wifi'|'dual_screen'|'bluetooth_drive'|'apk_document'|'r_mobiledata'|'lte_plus_mobiledata'|'stylus_note'|'dock_to_left'|'apk_install'|'timer_3_select'|'nearby_off'|'timer_10_select'|'dock_to_right'|'signal_cellular_null'|'brightness_alert'|'screen_record'|'h_mobiledata'|'network_locked'|'wifi_1_bar'|'media_bluetooth_off'|'portable_wifi_off'|'bigtop_updates'|'e_mobiledata'|'grid_goldenratio'|'h_plus_mobiledata'} IconSet86 */
/** @typedef {'splitscreen_vertical_add'|'screenshot_keyboard'|'display_external_input'|'battery_android_frame_full'|'keyboard_external_input'|'mobile_wrench'|'bolt_boost'|'battery_android_full'|'password_2'|'splitscreen_right'|'brightness_empty'|'screenshot_frame_2'|'android_wifi_4_bar'|'battery_android_5'|'battery_android_6'|'overview_key'|'battery_status_good'|'dock_to_bottom'|'android_wifi_3_bar'|'stylus'|'battery_android_frame_bolt'|'battery_android_bolt'|'splitscreen_add'|'contextual_token_add'|'battery_android_4'|'android_cell_4_bar'|'android_cell_5_bar'|'timer_5'|'screenshot_frame'|'splitscreen_left'|'keyboard_keys'|'battery_error'|'nearby'|'battery_plus'|'screenshot_region'} IconSet87 */
/** @typedef {'keyboard_full'|'wifi_home'|'magnify_docked'|'battery_android_3'|'keyboard_off'|'screen_rotation_up'|'android_wifi_3_bar_off'|'globe_2_question'|'splitscreen_top'|'backlight_low'|'battery_android_frame_4'|'android_cell_5_bar_off'|'android_cell_4_bar_alert'|'battery_android_frame_6'|'backlight_high_off'|'battery_android_2'|'1x_mobiledata_badge'|'splitscreen_bottom'|'wallpaper_slideshow'|'mobiledata_arrows'|'android_wifi_4_bar_off'|'network_wifi_3_bar_locked'|'keyboard_previous_language'|'battery_android_frame_1'|'network_wifi_locked'|'wifi_calling_bar_3'|'timer_5_shutter'|'backlight_high'|'battery_android_plus'|'battery_android_frame_2'|'5g_mobiledata_badge'|'battery_android_1'|'android_wifi_3_bar_alert'|'battery_android_0'|'magnify_fullscreen'} IconSet88 */
/** @typedef {'battery_android_frame_question'|'android_cell_5_bar_alert'|'android_wifi_3_bar_question'|'globe_2_cancel'|'password_2_off'|'battery_change'|'devices_fold_2'|'android_cell_4_bar_plus'|'wifi_notification'|'android_wifi_4_bar_plus'|'battery_android_shield'|'e_mobiledata_badge'|'android_wifi_4_bar_alert'|'battery_android_frame_3'|'3g_mobiledata_badge'|'android_cell_4_bar_off'|'android_wifi_4_bar_question'|'battery_android_frame_plus'|'graphic_eq_off'|'android_cell_5_bar_plus'|'g_mobiledata_badge'|'battery_android_alert'|'battery_android_frame_shield'|'network_wifi_1_bar_locked'|'wifi_calling_bar_2'|'battery_android_frame_5'|'keyboard_capslock_badge'|'keyboard_onscreen'|'android_wifi_3_bar_plus'|'grid_3x3_off'|'battery_android_question'|'android_cell_dual_4_bar_plus'|'mobile_sensor_hi'|'4g_mobiledata_badge'|'network_wifi_2_bar_locked'} IconSet89 */
/** @typedef {'battery_charging_30_2'|'android_cell_dual_4_bar_alert'|'battery_charging_20_2'|'android_cell_dual_5_bar_plus'|'battery_android_frame_alert'|'android_cell_dual_5_bar_alert'|'android_cell_dual_4_bar'|'computer'|'ev_mobiledata_badge'|'signal_cellular_pause'|'battery_share'|'light_mode_auto'|'battery_charging_50_2'|'keyboard_arrow_down'|'h_plus_mobiledata_badge'|'save'|'battery_charging_60_2'|'print'|'battery_android_share'|'lte_plus_mobiledata_badge'|'desktop_windows'|'signal_cellular_alt_off'|'wifi_calling_bar_1'|'android_wifi_3_bar_lock'|'android_wifi_4_bar_lock'|'devices'|'battery_charging_full_2'|'battery_charging_80_2'|'mobile_sensor_lo'|'nfc_off'|'h_mobiledata_badge'|'battery_android_frame_share'|'android_cell_dual_5_bar'|'lte_mobiledata_badge'} IconSet90 */
/** @typedef {'straight'|'keyboard_arrow_right'|'laptop_windows'|'router'|'smart_toy'|'cast_for_education'|'devices_other'|'point_of_sale'|'power'|'headphones'|'smart_display'|'tv'|'balance'|'device_thermostat'|'developer_board'|'memory'|'scale'|'route'|'keyboard'|'live_tv'|'watch'|'headset_mic'|'keyboard_arrow_up'|'keyboard_arrow_left'|'mouse'|'laptop_chromebook'|'keyboard_return'|'laptop_mac'|'device_hub'|'dns'|'cast'|'fax'|'videogame_asset'|'display_settings'|'keyboard_backspace'} IconSet91 */
/** @typedef {'sd_card'|'power_off'|'host'|'keyboard_hide'|'monitor'|'keyboard_capslock'|'important_devices'|'screenshot_monitor'|'screen_share'|'settings_remote'|'keyboard_alt'|'connected_tv'|'speaker_group'|'robot_2'|'tablet_mac'|'merge'|'settings_input_hdmi'|'punch_clock'|'mobile'|'tablet'|'settings_input_antenna'|'browser_updated'|'scanner'|'tablet_android'|'monitor_weight'|'remember_me'|'desktop_mac'|'speaker'|'print_disabled'|'sim_card'|'cast_connected'|'keyboard_tab'|'settings_input_component'|'screen_search_desktop'|'settings_ethernet'} IconSet92 */
/** @typedef {'google_home_devices'|'robot'|'mobile_3'|'headphones_battery'|'lift_to_talk'|'ramp_left'|'mobile_2'|'home_mini'|'head_mounted_device'|'roundabout_left'|'desktop_access_disabled'|'reset_tv'|'chromecast_device'|'home_max'|'no_sim'|'developer_board_off'|'tty'|'sd_card_alert'|'headset_off'|'devices_wearables'|'settop_component'|'earbuds_battery'|'disc_full'|'earbuds'|'watch_off'|'power_input'|'mobile_off'|'stop_screen_share'|'tv_off'|'roundabout_right'|'videogame_asset_off'|'joystick'|'adf_scanner'|'settings_input_svideo'|'ramp_right'} IconSet93 */
/** @typedef {'hard_disk'|'add_diamond'|'x_circle'|'computer_cancel'|'tv_displays'|'security_key'|'circle_circle'|'mobile_layout'|'mimo'|'developer_mode_tv'|'ecg'|'emoji_language'|'mobile_check'|'tv_options_input_settings'|'fitness_tracker'|'mobile_hand'|'desktop_cloud'|'memory_alt'|'camera_video'|'mobile_arrow_down'|'tv_options_edit_channels'|'watch_vibration'|'desktop_cloud_stack'|'touchpad_mouse'|'mobile_arrow_right'|'rear_camera'|'hard_drive'|'aod_tablet'|'device_band'|'jamboard_kiosk'|'media_output'|'devices_off'|'aod_watch'|'gamepad'|'reset_wrench'} IconSet94 */
/** @typedef {'plug_connect'|'p2p'|'tv_signin'|'mobile_lock_portrait'|'night_sight_max'|'general_device'|'mobile_sound_2'|'handheld_controller'|'mobile_code'|'fitness_trackers'|'hard_drive_2'|'mobile_block'|'server_person'|'watch_check'|'screenshot_tablet'|'keyboard_tab_rtl'|'mobile_gear'|'mobile_chat'|'computer_arrow_up'|'mobile_alert'|'mobile_vibrate'|'mobile_text_2'|'watch_arrow'|'tv_guide'|'tv_remote'|'smart_card_reader'|'cast_warning'|'watch_button_press'|'assistant_device'|'deskphone'|'mobile_hand_left'|'media_output_off'|'lightning_stand'|'mimo_disconnect'|'missing_controller'} IconSet95 */
/** @typedef {'touchpad_mouse_off'|'earbud_left'|'watch_wake'|'tablet_camera'|'earbud_case'|'mobile_camera'|'pacemaker'|'mobile_charge'|'router_off'|'mobile_rotate'|'save_clock'|'lda'|'arrows_left_right_circle'|'mouse_lock'|'audio_video_receiver'|'mobile_arrow_up_right'|'keyboard_lock'|'cast_pause'|'earbuds_2'|'mouse_lock_off'|'mobile_loupe'|'mobile_share'|'mobile_cast'|'mobile_question'|'mobile_info'|'open_jam'|'watch_lock'|'arrows_up_down_circle'|'mobile_screensaver'|'laptop_car'|'mobile_ticket'|'wifi_device'|'gamepad_circle_down'|'b_circle'|'mobile_speaker'} IconSet96 */
/** @typedef {'gamepad_circle_left'|'rectangle_add'|'square_circle'|'game_stick_left'|'computer_sound'|'print_add'|'smart_card_reader_off'|'game_button_zl'|'game_bumper_left'|'print_connect'|'mobile_lock_landscape'|'watch_arrow_down'|'print_error'|'mobile_unlock'|'y_circle'|'mobile_text'|'mobile_landscape'|'gamepad_circle_right'|'print_lock'|'mobile_rotate_lock'|'ventilator'|'keyboard_lock_off'|'triangle_circle'|'earbud_right'|'game_bumper_right'|'mobile_share_stack'|'game_button_l'|'game_button_r2'|'game_button_r'|'game_button_r1'|'gamepad_circle_up'|'watch_alert'|'tv_next'|'mobile_menu'|'game_button_l1'} IconSet97 */
/** @typedef {'game_stick_right'|'game_button_l2'|'mobile_hand_left_off'|'private_connectivity'|'enhanced_encryption'|'security'|'verified_user'|'gamepad_right'|'report'|'mobile_hand_off'|'vpn_lock'|'game_stick_r3'|'vpn_key'|'gamepad_down'|'game_stick_l3'|'watch_button'|'gamepad_left'|'shield'|'exclamation'|'badge'|'e911_emergency'|'assured_workload'|'disabled_visible'|'gamepad_up'|'passkey'|'admin_panel_settings'|'privacy_tip'|'mobile_dock'|'game_trigger_right'|'mobile_dots'|'policy'|'encrypted'|'game_button_zr'|'game_trigger_left'} IconSet98 */
/** @typedef {'mobile_theft'|'add_moderator'|'report_off'|'shield_person'|'id_card'|'id_card_2'|'vpn_key_off'|'sync_lock'|'shield_toggle'|'fitness_center'|'shield_locked'|'encrypted_off'|'spa'|'local_cafe'|'shield_lock'|'lunch_dining'|'remove_moderator'|'encrypted_add_circle'|'apartment'|'encrypted_add'|'cottage'|'no_encryption'|'vpn_key_alert'|'key_visualizer'|'identity_aware_proxy'|'shield_question'|'policy_alert'|'vpn_lock_2'|'shield_radar'|'wifi_password'|'shield_card'|'location_city'|'person_shield'|'encrypted_minus_circle'} IconSet99 */
/** @typedef {'liquor'|'family_restroom'|'festival'|'elevator'|'child_friendly'|'airline_seat_recline_normal'|'stairs'|'room_service'|'bakery_dining'|'nightlife'|'dinner_dining'|'villa'|'holiday_village'|'golf_course'|'sports_bar'|'food_bank'|'night_shelter'|'smoking_rooms'|'pool'|'other_houses'|'airplane_ticket'|'gite'|'hotel'|'escalator_warning'|'local_dining'|'local_bar'|'icecream'|'beach_access'|'smoke_free'|'museum'|'attractions'|'casino'|'luggage'|'ramen_dining'|'car_rental'} IconSet100 */
/** @typedef {'do_not_step'|'breakfast_dining'|'flights_and_hotels'|'escalator'|'chalet'|'concierge'|'airline_seat_flat'|'no_stroller'|'airline_seat_legroom_extra'|'tapas'|'wheelchair_pickup'|'airline_seat_recline_extra'|'rice_bowl'|'bungalow'|'airline_seat_flat_angled'|'no_luggage'|'travel'|'passport'|'personal_places'|'travel_luggage_and_bags'|'do_not_touch'|'houseboat'|'personal_bag'|'car_repair'|'airline_seat_individual_suite'|'airline_seat_legroom_reduced'|'no_drinks'|'no_food'|'brunch_dining'|'stairs_2'|'cabin'|'airline_seat_legroom_normal'|'trip'|'bento'|'carpenter'} IconSet101 */
/** @typedef {'carry_on_bag_inactive'|'coffee'|'okonomiyaki'|'house'|'checked_bag'|'mop'|'japanese_flag'|'kitchen'|'japanese_curry'|'child_care'|'checkroom'|'ac_unit'|'beer_meal'|'carry_on_bag_question'|'carry_on_bag'|'yoshoku'|'thermometer'|'shower'|'personal_bag_off'|'bath_bedrock'|'bed'|'chair'|'carry_on_bag_checked'|'mountain_steam'|'checked_bag_question'|'mode_fan'|'washoku'|'emergency_home'|'sensors'|'personal_bag_question'|'back_hand'|'grass'|'your_trips'|'electric_bolt'} IconSet102 */
/** @typedef {'flatware'|'chair_alt'|'coffee_maker'|'door_front'|'tv_gen'|'energy_savings_leaf'|'weekend'|'blender'|'humidity_mid'|'light'|'outdoor_grill'|'fireplace'|'mode_night'|'valve'|'garage_home'|'mode_heat'|'sensor_occupied'|'deck'|'window'|'bathtub'|'dining'|'garage'|'humidity_high'|'styler'|'yard'|'highlight'|'humidity_low'|'foundation'|'king_bed'|'scene'|'table_restaurant'|'electric_meter'|'roofing'|'cooking'|'bedroom_parent'} IconSet103 */
/** @typedef {'apparel'|'mode_cool'|'table_bar'|'bathroom'|'outlet'|'dishwasher_gen'|'switch'|'sprinkler'|'hardware'|'single_bed'|'propane_tank'|'energy_program_saving'|'gate'|'mode_off_on'|'in_home_mode'|'remote_gen'|'crib'|'living'|'water_damage'|'sensor_door'|'fire_extinguisher'|'event_seat'|'air_freshener'|'countertops'|'hot_tub'|'oven_gen'|'faucet'|'matter'|'bedroom_baby'|'home_iot_device'|'microwave'|'heat_pump'|'soap'|'detector_smoke'|'gas_meter'} IconSet104 */
/** @typedef {'smart_outlet'|'lightbulb_2'|'stroller'|'air_purifier_gen'|'emergency_share'|'energy_program_time_used'|'mode_fan_off'|'door_sliding'|'sensors_off'|'water_heater'|'camera_indoor'|'emergency_heat'|'bedroom_child'|'fence'|'health_and_beauty'|'hvac'|'balcony'|'mode_heat_cool'|'kettle'|'curtains'|'multicooker'|'family_home'|'blinds'|'umbrella'|'doorbell'|'desk'|'house_siding'|'camera_outdoor'|'iron'|'shield_moon'|'emergency_recording'|'wash'|'microwave_gen'|'dresser'|'door_back'} IconSet105 */
/** @typedef {'thermometer_gain'|'roller_shades'|'air_purifier'|'range_hood'|'light_off'|'home_improvement_and_tools'|'controller_gen'|'mode_heat_off'|'thermostat_auto'|'grocery'|'propane'|'thermostat_carbon'|'tamper_detection_off'|'vertical_shades_closed'|'tv_with_assistant'|'home_and_garden'|'fork_spoon'|'curtains_closed'|'dishwasher'|'blanket'|'doorbell_3p'|'blinds_closed'|'dry'|'mode_cool_off'|'skillet'|'garage_door'|'oven'|'household_supplies'|'vacuum'|'roller_shades_closed'|'vertical_shades'|'wall_art'|'sensor_window'|'shelves'|'thermometer_add'} IconSet106 */
/** @typedef {'hallway'|'bath_soak'|'mode_fan_2'|'fire_check'|'chair_umbrella'|'thermometer_alert'|'vacuum_2_on'|'stockpot'|'vacuum_2'|'emergency_heat_2'|'fragrance'|'door_open'|'lightstrip'|'chair_counter'|'chair_fireplace'|'speaker_2'|'stadia_controller'|'dine_heart'|'shades_closed'|'garage_door_open'|'subwoofer'|'dine_lamp'|'soundbar'|'blinds_2'|'emergency_share_off'|'skillet_cooktop'|'blinds_2_closed'|'thermometer_loss'|'table_large'|'switch_off'|'light_group_2'|'high_chair'|'thermometer_minus'|'shades'} IconSet107 */
/** @typedef {'battery_horiz_050'|'detection_and_zone'|'tools_ladder'|'nest_heat_link_gen_3'|'detector_alarm'|'settings_alert'|'nest_multi_room'|'home_storage'|'tools_power_drill'|'nest_cam_outdoor'|'nest_heat_link_e'|'tools_pliers_wire_stripper'|'nest_hello_doorbell'|'nest_eco_leaf'|'nest_remote_comfort_sensor'|'nest_secure_alarm'|'light_group'|'mfg_nest_yale_lock'|'nest_clock_farsight_analog'|'airwave'|'familiar_face_and_zone'|'cleaning_bucket'|'battery_horiz_000'|'google_wifi'|'shield_with_heart'|'weather_snowy'|'nest_display'|'early_on'|'arrows_more_up'|'battery_horiz_075'|'laundry'|'temp_preferences_eco'|'activity_zone'|'productivity'|'nest_cam_indoor'} IconSet108 */
/** @typedef {'zone_person_urgent'|'self_care'|'heat_pump_balance'|'floor_lamp'|'detector'|'nest_true_radiant'|'home_speaker'|'nest_found_savings'|'nest_thermostat_zirconium_eu'|'detector_status'|'nest_cam_floodlight'|'nest_mini'|'nest_cam_iq'|'tools_level'|'battery_profile'|'chromecast_2'|'nest_wifi_router'|'shield_with_house'|'window_open'|'window_closed'|'nest_thermostat_gen_3'|'nest_wifi_point'|'cool_to_dry'|'motion_sensor_active'|'house_with_shield'|'nest_clock_farsight_digital'|'nest_audio'|'nest_display_max'|'nest_cam_wired_stand'|'nest_farsight_weather'|'arming_countdown'|'nest_cam_iq_outdoor'|'home_max_dots'|'zone_person_alert'|'arrows_more_down'} IconSet109 */
/** @typedef {'nest_cam_stand'|'climate_mini_split'|'detector_battery'|'nest_cam_wall_mount'|'nest_cam_magnet_mount'|'nest_sunblock'|'nest_thermostat_sensor_eu'|'detector_offline'|'heat'|'wall_lamp'|'nest_doorbell_visitor'|'nest_tag'|'nest_connect'|'doorbell_chime'|'nest_thermostat_e_eu'|'nest_wake_on_press'|'zone_person_idle'|'detector_co'|'nest_thermostat'|'tools_flat_head'|'nest_detect'|'nest_wake_on_approach'|'door_sensor'|'motion_sensor_alert'|'google_tv_remote'|'tools_installation_kit'|'motion_sensor_idle'|'sensors_krx'|'nest_thermostat_sensor'|'window_sensor'|'tools_phillips'|'motion_sensor_urgent'|'table_lamp'|'water_pump'|'tamper_detection_on'} IconSet110 */
/** @typedef {'home_storage_gear'|'aq'|'sensors_krx_off'|'nest_wifi_pro_2'|'nest_wifi_pro'|'nest_farsight_seasonal'|'nest_farsight_cool'|'nest_farsight_dual'|'assistant_on_hub'|'farsight_digital'|'nest_farsight_eco'|'aq_indoor'|'on_hub_device'|'nest_farsight_heat'|'humidity_indoor'|'mode_dual'|'detection_and_zone_off'|'nest_protect'} IconSet111 */
/** @typedef {IconSet0|IconSet1|IconSet2|IconSet3|IconSet4|IconSet5|IconSet6|IconSet7|IconSet8|IconSet9|IconSet10|IconSet11|IconSet12|IconSet13|IconSet14|IconSet15|IconSet16|IconSet17|IconSet18|IconSet19|IconSet20|IconSet21|IconSet22|IconSet23|IconSet24|IconSet25|IconSet26|IconSet27|IconSet28|IconSet29|IconSet30|IconSet31|IconSet32|IconSet33|IconSet34|IconSet35|IconSet36|IconSet37|IconSet38|IconSet39|IconSet40|IconSet41|IconSet42|IconSet43|IconSet44|IconSet45|IconSet46|IconSet47|IconSet48|IconSet49|IconSet50|IconSet51|IconSet52|IconSet53|IconSet54|IconSet55|IconSet56|IconSet57|IconSet58|IconSet59|IconSet60|IconSet61|IconSet62|IconSet63|IconSet64|IconSet65|IconSet66|IconSet67|IconSet68|IconSet69|IconSet70|IconSet71|IconSet72|IconSet73|IconSet74|IconSet75|IconSet76|IconSet77|IconSet78|IconSet79|IconSet80|IconSet81|IconSet82|IconSet83|IconSet84|IconSet85|IconSet86|IconSet87|IconSet88|IconSet89|IconSet90|IconSet91|IconSet92|IconSet93|IconSet94|IconSet95|IconSet96|IconSet97|IconSet98|IconSet99|IconSet100|IconSet101|IconSet102|IconSet103|IconSet104|IconSet105|IconSet106|IconSet107|IconSet108|IconSet109|IconSet110|IconSet111} IconSet */

/**
 * @typedef {Object} IconOptions
 * @prop {100|200|300|400|500|600|700} weight Symbol weight
 * @prop {bool} fill
 * @prop {'low' | 'default' | 'high'} grade Symbol thickness
 * @prop {20|48} optical_size (from 20 to 48) For the image to look the same at different sizes in dp
 * @prop {number} size Icon size in px
 * @prop {string} color Any css-supported color variant (names, rgb, hex)
 */

var DEFAULT_ICON_COLOR = '#000'
var DEFAULT_ICON_SIZE = 24
/** @type {IconOptions} */
var DEFAULT_ICON_OPTIONS = {}

/** @type {Record<IconSet, (options: IconOptions) => HTMLSpanElement} */
const Icons = new Proxy(
    class {
        /**
         * @param {string} name 
         * @param {IconOptions} options 
         * @returns {HTMLSpanElement}
         */
        static getIcon(name, {fill, weight, grade, optical_size, size, color}) {
            const gr = ({
                'low': -25,
                'default': 0,
                'high': 200
            })[grade]
            const data = `
            'FILL' ${fill !== undefined ? fill?1:0 : 1}, 
            'wdth' ${weight || 400}, 
            'GRAD' ${gr || 0}, 
            'opsz' ${optical_size || 20}`
            const fz = size ? typeof size != Number  ? `${size}px`:size  : (DEFAULT_ICON_SIZE+'px')
            return $.span(
                {class: 'material-symbols-rounded icon', style: `font-size: ${fz}; width: ${fz}; height: ${fz}; ${color ? `color: ${color};` : ''}font-variation-settings: ${data}`},
                name
            )
        }
    },
    {
        get(target, name) {
            /**
             * @argument {IconOptions} options
             */
            return function(options) {
                return target.getIcon(name, options || DEFAULT_ICON_OPTIONS)
            }
        }
    }
)

// dont needed?
// const gIconsInit = () => document.head.innerHTML += `
//     <link rel="stylesheet" href="./gicons.lib.css">
// `

